### Get User Info
GET http://localhost:4000/userinfo
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImtleS0xIn0.eyJzdWIiOiJjbW83cTA3Z3IwMDAwMG02ZTA4YnpnMnY1IiwiYXVkIjoiY21vOGw2MzNmMDAwMWJ1NmV4Z3c5bjhvZSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJpYXQiOjE3NzY3OTI2MDMsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMCIsImV4cCI6MTc3Njc5MzUwM30.KnGcbHWH3JGaTDScxWDPqJ3thP_NMdAar7ruaOJo35gjh01O6N1FGmey32B23wVNLWBdPvcmAZx9qSGtV8bvfMPEGcsBqwlPofzEL1omrdBDP_lINcfgRR2oaXRGRrGNxlYtdlpUlBxW4g9f9VIa-q5ZFJx85J5EbYdnXceVlk1TQI2WFSX4DubSuvb9YGsk0b3mzuCz9R3kJcq31nA4TTqe30RfCEVRFpzcROdyNfLNTsIdowyOQtn0O0-Gq2522gJajOMBVvVPbWb_ZYLgYbMuMKBc5yoH76_0HXb6YB4mf8d6kUxMSK-PSpT0sP4Kctnxo8lvNcVL8vyMZy8Kmg
